name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Build Docker Image 
      run: docker build --build-arg VITE_API_URL='${{ secrets.VITE_API_URL }}' --build-arg VITE_API_BASE_URL='${{ secrets.VITE_API_BASE_URL }}' --build-arg VITE_S3_BUCKET='${{ secrets.VITE_S3_BUCKET }}' --build-arg VITE_AWS_REGION='${{ secrets.VITE_AWS_REGION }}' -t charlize367/pos_frontend:latest .
    - name: Publish Image to docker hub
      run: docker push charlize367/pos_frontend:latest


  deploy:
    needs: build
    runs-on: [self-hosted, frontend]
    steps:
      - name: Pull image from docker hub
        run: docker pull charlize367/pos_frontend:latest
      - name: Delete old container
        run: docker rm -f pos-frontend-container 
      - name: Run Docker container
        run: docker run -d -p 3000:80 --name pos-frontend-container  charlize367/pos_frontend:latest